language: android
before_script: cd code
jdk:
    - oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-23

    # Additional components

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    #- sys-img-x86-android-17

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - rvm install 2.0.0
  - gem install calabash-android
  - gem install cucumber 
before_script:
  - echo no | android create avd --force --name test --target android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -no-boot-anim &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 & #for unlocking as "powerkey"
  - sleep 3 # give screen some time to become unlocked
script:
  - ./gradlew clean assembleDebug -PdisablePreDex --continue --stacktrace
  - cd ../tests && calabash-android resign ../code/moneyControl/build/outputs/apk/moneyControl-debug.apk
  - calabash-android run ../code/moneyControl/build/outputs/apk/moneyControl-debug.apk
