#!/bin/bash
for photo in *.png; do 
	cp images_by_dimension/mipmap-xxhdpi/$photo ../../code/moneyControl/src/main/res/drawable-xxhdpi/$photo; 
	cp images_by_dimension/mipmap-xhdpi/$photo  ../../code/moneyControl/src/main/res/drawable-xhdpi/$photo; 
	cp images_by_dimension/mipmap-hdpi/$photo   ../../code/moneyControl/src/main/res/drawable-hdpi/$photo; 
	cp images_by_dimension/mipmap-mdpi/$photo   ../../code/moneyControl/src/main/res/drawable-mdpi/$photo; 
done
