CREATE TABLE TipoAtivo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE Ativo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
data DATE NOT NULL  DEFAULT 'NULL',
valor DECIMAL NOT NULL  DEFAULT NULL,
id_Conta INTEGER DEFAULT NULL REFERENCES Conta (id),
quantidade INTEGER NOT NULL  DEFAULT 1,
id_TipoAtivo INTEGER DEFAULT NULL REFERENCES TipoAtivo (id),
vencimento DATE NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE RentabilidadeAtivo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
data DATE NOT NULL  DEFAULT 'NULL',
valor DECIMAL NOT NULL  DEFAULT NULL,
id_Ativo INTEGER DEFAULT NULL REFERENCES Ativo (id)
);

CREATE TABLE EventoAtivo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL',
data DATE NOT NULL  DEFAULT 'NULL',
id_Ativo INTEGER DEFAULT NULL REFERENCES Ativo (id),
quantidade INTEGER NOT NULL  DEFAULT NULL,
valor DECIMAL NOT NULL  DEFAULT NULL,
id_TipoEventoAtivo TINYINT DEFAULT NULL REFERENCES TipoEventoAtivo (id)
);

CREATE TABLE TipoEventoAtivo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL'
);

INSERT INTO TipoAtivo (id, nome) VALUES(1, 'Ações');
INSERT INTO TipoAtivo (id, nome) VALUES(2, 'Tesouro Direto');
INSERT INTO TipoAtivo (id, nome) VALUES(3, 'CDB');
INSERT INTO TipoAtivo (id, nome) VALUES(4, 'Debênture');
INSERT INTO TipoAtivo (id, nome) VALUES(5, 'LCI');
INSERT INTO TipoAtivo (id, nome) VALUES(6, 'LCA');
INSERT INTO TipoAtivo (id, nome) VALUES(7, 'Poupança');
INSERT INTO TipoAtivo (id, nome) VALUES(8, 'Fundos Imobiliários');

INSERT INTO TipoEventoAtivo (id, nome) VALUES(1,'Compra');
INSERT INTO TipoEventoAtivo (id, nome) VALUES(2,'Venda');


