CREATE TABLE CartaoCredito (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
limite DECIMAL DEFAULT NULL,
dia_vencimento INTEGER NOT NULL  DEFAULT 1,
dia_fechamento INTEGER NOT NULL  DEFAULT 1,
id_Conta INTEGER DEFAULT NULL REFERENCES Conta (id)
);
