DROP TABLE Ativo;
DROP TABLE EventoATivo;

CREATE TABLE Ativo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
data DATE NOT NULL  DEFAULT 'NULL',
valor DECIMAL NOT NULL  DEFAULT NULL,
id_Conta INTEGER DEFAULT NULL REFERENCES Conta (id),
quantidade DECIMAL NOT NULL  DEFAULT 1,
id_TipoAtivo INTEGER DEFAULT NULL REFERENCES TipoAtivo (id),
vencimento DATE NOT NULL  DEFAULT 'NULL',
nome VARCHAR DEFAULT NULL,
sigla VARCHAR DEFAULT NULL
);

CREATE TABLE EventoAtivo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL',
data DATE NOT NULL  DEFAULT 'NULL',
id_Ativo INTEGER DEFAULT NULL REFERENCES Ativo (id),
quantidade DECIMAL NOT NULL  DEFAULT NULL,
valor DECIMAL NOT NULL  DEFAULT NULL,
id_TipoEventoAtivo INTEGER DEFAULT NULL REFERENCES TipoEventoAtivo (id)
);
