CREATE TABLE Bem (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL',
id_TipoBem INTEGER DEFAULT NULL REFERENCES TipoBem (id)
);

CREATE TABLE Conta (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR(200) NOT NULL  DEFAULT 'NULL',
saldo DECIMAL DEFAULT NULL,
icon INTEGER DEFAULT NULL,
id_TipoConta INTEGER DEFAULT NULL REFERENCES TipoConta (id)
);

CREATE TABLE Transacao (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
valor DECIMAL NOT NULL  DEFAULT NULL,
data DATE NOT NULL  DEFAULT 'NULL',
id_Conta INTEGER DEFAULT NULL REFERENCES Conta (id),
id_Bem INTEGER DEFAULT NULL REFERENCES Bem (id),
id_CategoriaTransacao INTEGER DEFAULT NULL REFERENCES CategoriaTransacao (id),
descricao VARCHAR DEFAULT NULL
);

CREATE TABLE TipoTransacao (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE TipoBem (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR(20) NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE TipoConta (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE CategoriaTransacao (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL',
id_TipoTransacao INTEGER DEFAULT NULL REFERENCES TipoTransacao (id),
system bit NOT NULL  DEFAULT 0
);

CREATE TABLE CartaoCredito (
id TINYINT DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
limite DECIMAL DEFAULT NULL,
dia_vencimento INT NOT NULL  DEFAULT 1,
dia_fechamento INTEGER NOT NULL  DEFAULT 1,
id_Conta INTEGER DEFAULT NULL REFERENCES Conta (id)
);

CREATE TABLE TipoAtivo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE Ativo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
data DATE NOT NULL  DEFAULT 'NULL',
valor DECIMAL NOT NULL  DEFAULT NULL,
id_Conta INTEGER DEFAULT NULL REFERENCES Conta (id),
quantidade DECIMAL NOT NULL  DEFAULT 1,
id_TipoAtivo INTEGER DEFAULT NULL REFERENCES TipoAtivo (id),
vencimento DATE NOT NULL  DEFAULT 'NULL',
nome VARCHAR DEFAULT NULL,
sigla VARCHAR DEFAULT NULL
);

CREATE TABLE RentabilidadeAtivo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
data DATE NOT NULL  DEFAULT 'NULL',
valor DECIMAL NOT NULL  DEFAULT NULL,
id_Ativo INTEGER DEFAULT NULL REFERENCES Ativo (id)
);

CREATE TABLE EventoAtivo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL',
data DATE NOT NULL  DEFAULT 'NULL',
id_Ativo INTEGER DEFAULT NULL REFERENCES Ativo (id),
quantidade DECIMAL NOT NULL  DEFAULT NULL,
valor DECIMAL NOT NULL  DEFAULT NULL,
id_TipoEventoAtivo INTEGER DEFAULT NULL REFERENCES TipoEventoAtivo (id)
);

CREATE TABLE TipoEventoAtivo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL'
);


