


CREATE TABLE Bem (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL',
id_TipoBem INTEGER DEFAULT NULL REFERENCES TipoBem (id)
);

CREATE TABLE Conta (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR(200) NOT NULL  DEFAULT 'NULL',
saldo DECIMAL DEFAULT NULL,
icon INTEGER DEFAULT NULL,
id_TipoConta INTEGER DEFAULT NULL REFERENCES TipoConta (id)
);

CREATE TABLE Transacao (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
valor DECIMAL NOT NULL  DEFAULT NULL,
data DATE NOT NULL  DEFAULT 'NULL',
id_Conta INTEGER DEFAULT NULL REFERENCES Conta (id),
id_Bem INTEGER DEFAULT NULL REFERENCES Bem (id),
id_CategoriaTransacao INTEGER DEFAULT NULL REFERENCES CategoriaTransacao (id),
descricao VARCHAR DEFAULT NULL
);

CREATE TABLE TipoTransacao (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE TipoBem (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR(20) NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE TipoConta (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE CategoriaTransacao (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL',
id_TipoTransacao INTEGER DEFAULT NULL REFERENCES TipoTransacao (id)
);



