CREATE TABLE ContaPaga (
id INTEGER NOT NULL  PRIMARY KEY AUTOINCREMENT,
id_ContaAPagar INTEGER NOT NULL  DEFAULT NULL REFERENCES ContaAPagar (id),
id_Transacao INTEGER NOT NULL  REFERENCES Transacao (id),
vencimento DATE NOT NULL 
);
