CREATE TABLE Compra (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
valor DECIMAL DEFAULT NULL,
parcelas INTEGER NOT NULL  DEFAULT 1,
data DATE NOT NULL  DEFAULT 'NULL',
descricao VARCHAR DEFAULT NULL,
id_Conta INTEGER DEFAULT NULL REFERENCES Conta (id),
id_CategoriaTransacao INTEGER DEFAULT NULL REFERENCES CategoriaTransacao (id)
);

ALTER TABLE Transacao ADD executada bit NOT NULL DEFAULT 1;
ALTER TABLE Transacao ADD id_Compra INTEGER DEFAULT NULL REFERENCES Compra (id);
