CREATE TABLE Bem (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL',
id_TipoBem INTEGER DEFAULT NULL REFERENCES TipoBem (id)
);

CREATE TABLE Conta (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR(200) NOT NULL  DEFAULT 'NULL',
saldo DECIMAL DEFAULT NULL,
icon VARCHAR(200) DEFAULT NULL,
id_TipoConta INTEGER DEFAULT NULL REFERENCES TipoConta (id)
);

CREATE TABLE Transacao (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
valor DECIMAL NOT NULL  DEFAULT NULL,
data DATE NOT NULL  DEFAULT 'NULL',
id_Conta INTEGER DEFAULT NULL REFERENCES Conta (id),
id_Bem INTEGER DEFAULT NULL REFERENCES Bem (id),
id_CategoriaTransacao INTEGER DEFAULT NULL REFERENCES CategoriaTransacao (id),
descricao VARCHAR DEFAULT NULL,
executada bit NOT NULL  DEFAULT 1,
id_Compra INTEGER DEFAULT NULL REFERENCES Compra (id),
id_DespesasFuturas INTEGER NOT NULL  DEFAULT NULL,
id_ContaAPagar INTEGER NOT NULL  DEFAULT NULL REFERENCES ContaAPagar (id)
);

CREATE TABLE TipoTransacao (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE TipoBem (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR(20) NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE TipoConta (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL'
);

CREATE TABLE CategoriaTransacao (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR NOT NULL  DEFAULT 'NULL',
id_TipoTransacao INTEGER DEFAULT NULL REFERENCES TipoTransacao (id),
system bit NOT NULL  DEFAULT 0
);

CREATE TABLE CartaoCredito (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
limite DECIMAL DEFAULT NULL,
dia_vencimento INT NOT NULL  DEFAULT 1,
dia_fechamento INTEGER NOT NULL  DEFAULT 1,
id_Conta INTEGER DEFAULT NULL REFERENCES Conta (id)
);

CREATE TABLE Ativo (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
nome VARCHAR DEFAULT NULL
);

CREATE TABLE MovimentacaoAtivo (
id INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
data DATE NOT NULL  DEFAULT 'NULL',
financeiro DECIMAL DEFAULT NULL,
movimentacao DECIMAL DEFAULT NULL,
id_Ativo INTEGER DEFAULT NULL REFERENCES Ativo (id),
patrimonio DECIMAL DEFAULT NULL,
cotas DECIMAL DEFAULT NULL,
cotas_emitidas DECIMAL DEFAULT NULL,
id_Transacao INTEGER DEFAULT NULL REFERENCES Transacao (id)
);

CREATE TABLE ContaAPagar (
id INTEGER NOT NULL  DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
valor DECIMAL DEFAULT NULL,
data DATE NOT NULL  DEFAULT 'NULL',
descricao VARCHAR(200) NOT NULL  DEFAULT 'NULL',
status bit NOT NULL  DEFAULT 1,
id_Repeticao INTEGER DEFAULT NULL REFERENCES Repeticao (id),
id_CategoriaTransacao INTEGER DEFAULT NULL REFERENCES CategoriaTransacao (id)
);

CREATE TABLE Orcamento (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
mes DATE NOT NULL  DEFAULT 'NULL',
id_CategoriaTransacao INTEGER DEFAULT NULL REFERENCES CategoriaTransacao (id),
valor DECIMAL NOT NULL  DEFAULT NULL
);

CREATE TABLE Compra (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
valor DECIMAL DEFAULT NULL,
parcelas INTEGER NOT NULL  DEFAULT 1,
data DATE NOT NULL  DEFAULT 'NULL',
descricao VARCHAR DEFAULT NULL,
id_Conta INTEGER DEFAULT NULL REFERENCES Conta (id),
id_CategoriaTransacao INTEGER DEFAULT NULL REFERENCES CategoriaTransacao (id)
);

CREATE TABLE Repeticao (
id INTEGER DEFAULT NULL PRIMARY KEY AUTOINCREMENT,
tipo VARCHAR(50) NOT NULL  DEFAULT 'NULL'
);

